language: clojure
lein: lein2
before_script:
- lein2 version
- lein2 deps :tree
script: lein2 test
after_success:
- lein2 pallet-release push
env:
  global:
    secure: I+fU/887JA75/HGklmowI8YvaaMhPz0/UP50ws8XFNu8KCn40QpaxAkatE65OleRjjMNp27ORsQNbg3rIk5oY+Vyp7+OsVB+bgGvYuK7iLIkVvAKDvITyH2D0uG3AongGyYkH+ACdMqm4re2RZne1mbXHbNxKSqauOdWconamRQ=
